version: '3'
services:
  graphic-app:
    build: .
    image: graphic_app
    environment:
      - DISPLAY=${HOSTNAME}${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - influxdata
      - mosq

  web-var-change-app:
    build: .
    image: var_change
    command: python3 -m web_mqtt
    ports:
    - '2155:2155'
    depends_on:
      - influxdata
      - mosq

  influxdata:
    image: influxdb:latest
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=baza

  mosq:
    image: ansi/mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883