version: '3'
services:
  vars:
    build: .
    image: vars
    environment:
      - DISPLAY=${HOSTNAME}${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - influxdata


  influxdata:
    image: influxdb:latest
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=baza
